name: Update Private Packagist

on: push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger webhook
      uses: magdemajt/trigger-webhook@v1
      with:
        # URL to send the request to
        url: ${{ secrets.WEBHOOK_URL }}
