name: Update Private Packagist

on: push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Webhook Trigger
      uses: zzzze/webhook-trigger@v1.0.0
      with:
        # Endpoint URL
        webhook_url: ${{ secrets.WEBHOOK_URL }}
